@startuml
class baseline.writingFile {
- FileWriter writer
- int countModify
- ArrayList<String> list
+ int getCountModify()
+ void getModification()
}
class baseline.FileRead {
- ArrayList<String> list
- Scanner scanner
- void readile()
+ ArrayList<String> getData()
}
class baseline.solution45 {
+ {static} void main(String[])
}
@enduml